//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace editdocuments {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("editdocuments.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execution ended in all selected files..
        /// </summary>
        internal static string ExecutionCompletedDefaultMessage {
            get {
                return ResourceManager.GetString("ExecutionCompletedDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execution completed.
        /// </summary>
        internal static string ExecutionCompletedTitle {
            get {
                return ResourceManager.GetString("ExecutionCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execution error.
        /// </summary>
        internal static string ExecutionErrorTitle {
            get {
                return ResourceManager.GetString("ExecutionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closing MS Word in background.
        /// </summary>
        internal static string InfoCloseWord {
            get {
                return ResourceManager.GetString("InfoCloseWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File {0} /{1}.
        /// </summary>
        internal static string InfoCounterFile {
            get {
                return ResourceManager.GetString("InfoCounterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The directory {0} was created sucessfully at {1}.
        /// </summary>
        internal static string InfoCreateDirectorySuccess {
            get {
                return ResourceManager.GetString("InfoCreateDirectorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current file name: {0}.
        /// </summary>
        internal static string InfoFileName {
            get {
                return ResourceManager.GetString("InfoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish processing file {0}.
        /// </summary>
        internal static string InfoFinishFile {
            get {
                return ResourceManager.GetString("InfoFinishFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish processing files..
        /// </summary>
        internal static string InfoFinishProcessingFiles {
            get {
                return ResourceManager.GetString("InfoFinishProcessingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish program.
        /// </summary>
        internal static string InfoFinishProgram {
            get {
                return ResourceManager.GetString("InfoFinishProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no.
        /// </summary>
        internal static string InfoNo {
            get {
                return ResourceManager.GetString("InfoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting MS Word in background.
        /// </summary>
        internal static string InfoOpenWord {
            get {
                return ResourceManager.GetString("InfoOpenWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page {0} is out of the document bounds. Image not inserted..
        /// </summary>
        internal static string InfoPageOutOfBounds {
            get {
                return ResourceManager.GetString("InfoPageOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Placeholder set to: {0}.
        /// </summary>
        internal static string InfoPlaceholder {
            get {
                return ResourceManager.GetString("InfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved PDF file: {0}.
        /// </summary>
        internal static string InfoSavedPDFFile {
            get {
                return ResourceManager.GetString("InfoSavedPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save word document: {0}.
        /// </summary>
        internal static string InfoSaveWordDocument {
            get {
                return ResourceManager.GetString("InfoSaveWordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processsing file: {0}.
        /// </summary>
        internal static string InfoStartFile {
            get {
                return ResourceManager.GetString("InfoStartFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting processing {0} files..
        /// </summary>
        internal static string InfoStartProcessingFiles {
            get {
                return ResourceManager.GetString("InfoStartProcessingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting program.
        /// </summary>
        internal static string InfoStartProgram {
            get {
                return ResourceManager.GetString("InfoStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total documents with inserted image successfully: {0}/{1}.
        /// </summary>
        internal static string InfoSummarySuccess {
            get {
                return ResourceManager.GetString("InfoSummarySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text &quot;{0}&quot; not found in document. Image not inserted..
        /// </summary>
        internal static string InfoTextNotFound {
            get {
                return ResourceManager.GetString("InfoTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yes.
        /// </summary>
        internal static string InfoYes {
            get {
                return ResourceManager.GetString("InfoYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to save the current settings?.
        /// </summary>
        internal static string QuerySaveCurrentValues {
            get {
                return ResourceManager.GetString("QuerySaveCurrentValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save current settings.
        /// </summary>
        internal static string SaveCurrentValues {
            get {
                return ResourceManager.GetString("SaveCurrentValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is required a valid file path.
        ///Use the Explorer button to select one..
        /// </summary>
        internal static string TextValidationFilePath {
            get {
                return ResourceManager.GetString("TextValidationFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is required a valid picture path.
        ///Use the Explorer button to select one..
        /// </summary>
        internal static string TextValidationPicturePath {
            get {
                return ResourceManager.GetString("TextValidationPicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is required a non-empty placeholder..
        /// </summary>
        internal static string TextValidationPlaceholder {
            get {
                return ResourceManager.GetString("TextValidationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is required a non-empty subfolder name..
        /// </summary>
        internal static string TextValidationSubFolder {
            get {
                return ResourceManager.GetString("TextValidationSubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How to use.
        /// </summary>
        internal static string TitleHowToUse {
            get {
                return ResourceManager.GetString("TitleHowToUse", resourceCulture);
            }
        }
    }
}
