//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace editdocuments {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("editdocuments.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execution ended in all selected files..
        /// </summary>
        internal static string ExecutionCompletedDefaultMessage {
            get {
                return ResourceManager.GetString("ExecutionCompletedDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execution completed.
        /// </summary>
        internal static string ExecutionCompletedTitle {
            get {
                return ResourceManager.GetString("ExecutionCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execution error.
        /// </summary>
        internal static string ExecutionErrorTitle {
            get {
                return ResourceManager.GetString("ExecutionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the page reference to the bottom left corner of the selected page..
        /// </summary>
        internal static string HelpBottomLeft {
            get {
                return ResourceManager.GetString("HelpBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the page reference to the bottom right corner of the selected page..
        /// </summary>
        internal static string HelpBottomRight {
            get {
                return ResourceManager.GetString("HelpBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current unit for Width, Height, LeftOffset and BottomOffset. If changed, all values are updated to its equivalence..
        /// </summary>
        internal static string HelpCurrentUnit {
            get {
                return ResourceManager.GetString("HelpCurrentUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click to insert the image in selected files and save resulting documents as PDFs..
        /// </summary>
        internal static string HelpGenerate {
            get {
                return ResourceManager.GetString("HelpGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance from the reference point to the bottom side of the image. Measured in the selected unit..
        /// </summary>
        internal static string HelpImageBottomOffset {
            get {
                return ResourceManager.GetString("HelpImageBottomOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current image height in the selected unit..
        /// </summary>
        internal static string HelpImageHeight {
            get {
                return ResourceManager.GetString("HelpImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance from the reference point to the left side of the image. Measured in the selected unit..
        /// </summary>
        internal static string HelpImageLeftOffset {
            get {
                return ResourceManager.GetString("HelpImageLeftOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image preview for current selected picture..
        /// </summary>
        internal static string HelpImagePreview {
            get {
                return ResourceManager.GetString("HelpImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current image width in the selected unit..
        /// </summary>
        internal static string HelpImageWidth {
            get {
                return ResourceManager.GetString("HelpImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current input file/folder path. Click on &quot;Explore&quot; to select one..
        /// </summary>
        internal static string HelpInputPath {
            get {
                return ResourceManager.GetString("HelpInputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click to select the files/folder to be processed..
        /// </summary>
        internal static string HelpInputPathExplore {
            get {
                return ResourceManager.GetString("HelpInputPathExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the input path as a list of files, separated by commas &quot;,&quot;.
        /// </summary>
        internal static string HelpInputPathFiles {
            get {
                return ResourceManager.GetString("HelpInputPathFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the input path as a folder..
        /// </summary>
        internal static string HelpInputPathFolder {
            get {
                return ResourceManager.GetString("HelpInputPathFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantain the aspect ratio for the image. If modify width, the height is modified accordingly..
        /// </summary>
        internal static string HelpKeepAspectRatio {
            get {
                return ResourceManager.GetString("HelpKeepAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page number where the image is inserted..
        /// </summary>
        internal static string HelpPageNumber {
            get {
                return ResourceManager.GetString("HelpPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select PDF as input document type..
        /// </summary>
        internal static string HelpPDFSelection {
            get {
                return ResourceManager.GetString("HelpPDFSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current picture path. Click on &quot;Explore&quot; to select one..
        /// </summary>
        internal static string HelpPicturePath {
            get {
                return ResourceManager.GetString("HelpPicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click to select the picture to be inserted in document(s)..
        /// </summary>
        internal static string HelpPicturePathExplore {
            get {
                return ResourceManager.GetString("HelpPicturePathExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text to be searched in document and where the image will be placed..
        /// </summary>
        internal static string HelpPlaceHolder {
            get {
                return ResourceManager.GetString("HelpPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the reference to the corners in the page. Only for PDF documents..
        /// </summary>
        internal static string HelpRelativeToPage {
            get {
                return ResourceManager.GetString("HelpRelativeToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the reference to a text placeholder in the document..
        /// </summary>
        internal static string HelpRelativeToText {
            get {
                return ResourceManager.GetString("HelpRelativeToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save the PDF in the same folder as the original file. Only for Word documents..
        /// </summary>
        internal static string HelpSameFolder {
            get {
                return ResourceManager.GetString("HelpSameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save the PDF in a subfolder relative to the directory of the current file..
        /// </summary>
        internal static string HelpSubFolder {
            get {
                return ResourceManager.GetString("HelpSubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the subfolder name to save the generated PDF file..
        /// </summary>
        internal static string HelpSubFolderText {
            get {
                return ResourceManager.GetString("HelpSubFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the page reference to the top left corner of the selected page..
        /// </summary>
        internal static string HelpTopLeft {
            get {
                return ResourceManager.GetString("HelpTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the page reference to the top right corner of the selected page..
        /// </summary>
        internal static string HelpTopRight {
            get {
                return ResourceManager.GetString("HelpTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Word as input document type..
        /// </summary>
        internal static string HelpWordSelection {
            get {
                return ResourceManager.GetString("HelpWordSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closing MS Word in background.
        /// </summary>
        internal static string InfoCloseWord {
            get {
                return ResourceManager.GetString("InfoCloseWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File {0} /{1}.
        /// </summary>
        internal static string InfoCounterFile {
            get {
                return ResourceManager.GetString("InfoCounterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The directory {0} was created sucessfully at {1}.
        /// </summary>
        internal static string InfoCreateDirectorySuccess {
            get {
                return ResourceManager.GetString("InfoCreateDirectorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current file name: {0}.
        /// </summary>
        internal static string InfoFileName {
            get {
                return ResourceManager.GetString("InfoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish processing file {0}.
        /// </summary>
        internal static string InfoFinishFile {
            get {
                return ResourceManager.GetString("InfoFinishFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish processing files..
        /// </summary>
        internal static string InfoFinishProcessingFiles {
            get {
                return ResourceManager.GetString("InfoFinishProcessingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish program.
        /// </summary>
        internal static string InfoFinishProgram {
            get {
                return ResourceManager.GetString("InfoFinishProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no.
        /// </summary>
        internal static string InfoNo {
            get {
                return ResourceManager.GetString("InfoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting MS Word in background.
        /// </summary>
        internal static string InfoOpenWord {
            get {
                return ResourceManager.GetString("InfoOpenWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page {0} is out of the document bounds. Image not inserted..
        /// </summary>
        internal static string InfoPageOutOfBounds {
            get {
                return ResourceManager.GetString("InfoPageOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Placeholder set to: {0}.
        /// </summary>
        internal static string InfoPlaceholder {
            get {
                return ResourceManager.GetString("InfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved PDF file: {0}.
        /// </summary>
        internal static string InfoSavedPDFFile {
            get {
                return ResourceManager.GetString("InfoSavedPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save word document: {0}.
        /// </summary>
        internal static string InfoSaveWordDocument {
            get {
                return ResourceManager.GetString("InfoSaveWordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processsing file: {0}.
        /// </summary>
        internal static string InfoStartFile {
            get {
                return ResourceManager.GetString("InfoStartFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting processing {0} files..
        /// </summary>
        internal static string InfoStartProcessingFiles {
            get {
                return ResourceManager.GetString("InfoStartProcessingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starting program.
        /// </summary>
        internal static string InfoStartProgram {
            get {
                return ResourceManager.GetString("InfoStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File explorer opened..
        /// </summary>
        internal static string InfoStatusFileExplorerOpen {
            get {
                return ResourceManager.GetString("InfoStatusFileExplorerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder explorer opened..
        /// </summary>
        internal static string InfoStatusFolderExplorerOpen {
            get {
                return ResourceManager.GetString("InfoStatusFolderExplorerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The processing is executing in another dialog..
        /// </summary>
        internal static string InfoStatusNewDialogProcessing {
            get {
                return ResourceManager.GetString("InfoStatusNewDialogProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The processing has finished..
        /// </summary>
        internal static string InfoStatusProcessingFinished {
            get {
                return ResourceManager.GetString("InfoStatusProcessingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        internal static string InfoStatusReady {
            get {
                return ResourceManager.GetString("InfoStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The processing has started..
        /// </summary>
        internal static string InfoStatusStartProcessing {
            get {
                return ResourceManager.GetString("InfoStatusStartProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some validations were not successful. Please, check the blinking alerts and fix them..
        /// </summary>
        internal static string InfoStatusValidationError {
            get {
                return ResourceManager.GetString("InfoStatusValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total documents with inserted image successfully: {0}/{1}.
        /// </summary>
        internal static string InfoSummarySuccess {
            get {
                return ResourceManager.GetString("InfoSummarySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text &quot;{0}&quot; not found in document. Image not inserted..
        /// </summary>
        internal static string InfoTextNotFound {
            get {
                return ResourceManager.GetString("InfoTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yes.
        /// </summary>
        internal static string InfoYes {
            get {
                return ResourceManager.GetString("InfoYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to save the current settings?.
        /// </summary>
        internal static string QuerySaveCurrentValues {
            get {
                return ResourceManager.GetString("QuerySaveCurrentValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save current settings.
        /// </summary>
        internal static string SaveCurrentValues {
            get {
                return ResourceManager.GetString("SaveCurrentValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is required a valid file path.
        ///Use the Explorer button to select one..
        /// </summary>
        internal static string TextValidationFilePath {
            get {
                return ResourceManager.GetString("TextValidationFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is required a valid picture path.
        ///Use the Explorer button to select one..
        /// </summary>
        internal static string TextValidationPicturePath {
            get {
                return ResourceManager.GetString("TextValidationPicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is required a non-empty placeholder..
        /// </summary>
        internal static string TextValidationPlaceholder {
            get {
                return ResourceManager.GetString("TextValidationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is required a non-empty subfolder name..
        /// </summary>
        internal static string TextValidationSubFolder {
            get {
                return ResourceManager.GetString("TextValidationSubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How to use.
        /// </summary>
        internal static string TitleHowToUse {
            get {
                return ResourceManager.GetString("TitleHowToUse", resourceCulture);
            }
        }
    }
}
